# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']
  pull_request: #remove later, just for testing

name: render-rmarkdown.yaml

permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          # Specify a specific R version or 'release' now that renv is not used
          r-version: 'release'

      - name: Install R dependencies
        run: |
          install.packages(c("rmarkdown", "knitr"))
          # Add any other R packages needed to render your Rmd files here
          # install.packages(c("ggplot2", "dplyr", "readr"))
        shell: Rscript {0}

      - name: Render Rmarkdown files and Commit Results
        run: |
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          # Check if RMD_PATH array is empty
          if [ ${#RMD_PATH[@]} -eq 0 ]; then
            echo "No .Rmd files changed."
            exit 0
          fi
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          # Create a list of the corresponding .md files
          MD_FILES=()
          for rmd in "${RMD_PATH[@]}"; do
            MD_FILES+=("${rmd/.Rmd/.md}")
          done
          git add "${MD_FILES[@]}"
          git commit -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
