# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']

name: render-rmarkdown.yaml

permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      # Use the bot's PAT for any R package installs (e.g., from private repos)
      GITHUB_PAT: ${{ secrets.BOT_PAT }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This is the most important change.
          # It uses the bot's token to check out the repo.
          # This configures the 'git' remote to use this token for the 'git push' later.
          token: ${{ secrets.BOT_PAT }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render Rmarkdown files and Commit Results
        run: |
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}

          # --- Change 1: Set the committer name to the bot ---
          git config --local user.name "pharmaverse-bot"

          # --- Change 2: Set the committer email to the bot ---
          git config --local user.email "pharmaverse-bot@users.noreply.github.com"

          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
